# Generated by Django 3.2.16 on 2023-05-25 05:12

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(db_column='catId', default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(db_column='catName', max_length=50)),
            ],
            options={
                'db_table': 'CATEGORY',
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.UUIDField(db_column='offId', default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='offCreatedAt')),
                ('amount', models.DecimalField(db_column='offAmount', decimal_places=0, max_digits=13)),
                ('available', models.BooleanField(db_column='offAvailable', default=True)),
            ],
            options={
                'db_table': 'OFFER',
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.UUIDField(db_column='pubId', default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(db_column='pubTitle', max_length=50)),
                ('description', models.CharField(db_column='pubDescription', max_length=256)),
                ('minOffer', models.DecimalField(db_column='pubMinOffer', decimal_places=0, max_digits=13)),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='pubCreatedAt')),
                ('endDate', models.DateTimeField(db_column='pubEndDate', default=datetime.datetime(2023, 5, 26, 0, 12, 43, 315749))),
                ('available', models.BooleanField(db_column='pubAvailable', default=True)),
                ('reportable', models.BooleanField(db_column='pubReportable', default=True)),
                ('priority', models.BooleanField(db_column='pubPriority', default=False)),
                ('deliveryType', models.CharField(choices=[('SV', 'Servientrega'), ('PS', 'Prosegur')], db_column='pubDeliveryType', max_length=2, null=True)),
                ('deliveryId', models.CharField(db_column='pubDeliveryId', max_length=45, null=True)),
                ('confirmed', models.BooleanField(db_column='pubConfirmed', default=False)),
                ('category', models.ForeignKey(db_column='catId', on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='publications.category')),
            ],
            options={
                'db_table': 'PUBLICATION',
            },
        ),
        migrations.CreateModel(
            name='PublicationSupport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO', 'Video')], db_column='sopType', max_length=45)),
                ('data', models.URLField(db_column='sopData')),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='sopCreatedAt')),
                ('description', models.CharField(db_column='sopDescription', max_length=255)),
                ('publication', models.ForeignKey(db_column='pubId', on_delete=django.db.models.deletion.CASCADE, related_name='supports', to='publications.publication')),
            ],
            options={
                'db_table': 'PUBLICATIONSUPPORT',
            },
        ),
    ]
