# Generated by Django 3.2.16 on 2023-05-25 05:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('publications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='user',
            field=models.ForeignKey(db_column='usrId', on_delete=django.db.models.deletion.CASCADE, related_name='publications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='offer',
            name='publication',
            field=models.ForeignKey(db_column='pubId', on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='publications.publication'),
        ),
        migrations.AddField(
            model_name='offer',
            name='user',
            field=models.ForeignKey(db_column='usrId', on_delete=django.db.models.deletion.CASCADE, related_name='offers', to=settings.AUTH_USER_MODEL),
        ),
    ]
