# Generated by Django 3.2.16 on 2023-05-25 05:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(db_column='notId', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='notTitle', max_length=100, null=True)),
                ('description', models.CharField(db_column='notDescription', max_length=255, null=True)),
                ('isRead', models.BooleanField(db_column='notIsRead', default=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='notCreatedAt')),
            ],
            options={
                'db_table': 'NOTIFICATION',
            },
        ),
    ]
